### ISSUE TITLE
Error in nova-demo example

### ISSUE THREAD

**Issue by vonwao** [meteor-utilities/smart-publications#1]
I tried to extract just the nova-demo example, for this also needed some other packages:
nova-core, nova-events, nova-i18n, nova-lib, nova-settings

When I ran it, I got this error in smart-publications:

=> App running at: http://localhost:3000/
I20160301-23:44:30.356(-5)? Exception from sub movies.list id gJXKAKCTed3YcTnmC TypeError: Cannot read property '_schema' of null
I20160301-23:44:30.357(-5)?     at [object Object].Mongo.Collection.getPublishedFields (packages/utilities:smart-publications/lib/smart-publications.js:125:16)
I20160301-23:44:30.357(-5)?     at packages/utilities:smart-publications/lib/smart-publications.js:27:51

**Comment by SachaG** [comment]
It sounds like your collection doesn't have a SimpleSchema schema?

**Comment by vonwao** [comment]
I'm using the exact code in the nova-demo package.  It calls 
Movies.attachSchema(schema);

The /demo route loads ok, the MoviesWrapper displays, then it goes into an infinite loop or errors!

Something else must be missing, but I don't know what.

**Comment by vonwao** [comment]
There must be something in another nova package, some is having a side effect that is required?

**Comment by SachaG** [comment]
Can you share your code?

**Comment by SachaG** [comment]
I think the problem happens when the package attempts to find the joined collection. Maybe just remove the join for now?

**Comment by vonwao** [comment]
Yes, that fixed it.  Thanks!
